### PR TITLE
Added fsfreeze support for all Clusternodes

### PR DESCRIPTION
**Pull request by lephisto**
You might want to review this and merge if helpful

### CODE REVIEW

**Comment by aderumier** [comment]
Hi,I'll try to test it next week

https://github.com/Corsinvest/cv4pve-barc/issues/30

**Comment by franklupo** [comment]
Good. I test version in next week

**Comment by lephisto** [comment]
I continue some improvement work meanwhile

**Comment by franklupo** [comment]
instead of running ssh on each host you could look at the file in the /etc/pve/nodes/%host%/qemu-server/ or /etc/pve/nodes/%host%/lxc/ directory as I already do

**Comment by lephisto** [comment]
I ssh to the hosts to be able to issue qemu cmd's .. that won't work if the guest is not running on the host you're running the backup on.

**Comment by lephisto** [comment]
Ah, i know what you mean, probably map_vmids_to_host(), which i use to get a consitent map of host->vmid. This could be made locally. Still my method respectd the quorum, since it uses straightly the API. But you can re-work it, or just cherrypick other stuff you want. Nevermind..

**Comment by lephisto** [comment]
I did a bunch of more stuff, i so i open a new pr, since i have those (many) changes in a feature branch..

**Pull request closed without merging**
