### PR TITLE
fsfreeze support + improved reporting + renew policy + checksumming + compression

### PR DESCRIPTION
**Pull request by lephisto**
This includes the changes from the previous PR as well as the option, to renew the full backup every X Snapshots to increase safety on Backups. In the original version you would rely on never getting problems with your storage and a resilvering filesystem underneath.

Review would be nice.

### CODE REVIEW

**Comment by franklupo** [comment]
Good.
What do you think of moving fsfreeze from the hook script into the main script?
If necessary we create a parameter --qemu-freeze

Best regards

**Comment by lephisto** [comment]
Yes sure, this could be done. Still, i'm working on making the restore function with the whiptail options compatible with the renew options..

**Comment by lephisto** [comment]
I added some more stuff. maybe you wanna look at it..

**Comment by franklupo** [comment]
In the next days i test fix
Best regards

**Comment by franklupo** [comment]
Don't use eval but do_run(). This fiction support parametr dry-run for testing.--try-run and --debug is not documentate but show comand and no esecute

**Comment by franklupo** [comment]
Freeze work only qemu no Lxc. Filter execution only qemu.

**Comment by lephisto** [comment]
OK, will change this evening..

**Comment by franklupo** [comment]
How work import if compress backup?

**Comment by lephisto** [comment]
Restore w/ compression is still WIP.

**Comment by lephisto** [comment]
There's a ton of changes now.. restore with decompress / checksum validation is in now, i did some tests. Other testers welcome :)

**Comment by lephisto** [comment]
Ideas:

- Auto-Restore test (Test if Snapshots restore properly and fsck runs smooth)
- Fix Datehandling in Status routines
- Config Storage to get rid of clumsy commandlines.

**Comment by franklupo** [comment]
Great ideas.
But first I think it's worth testing this code and then releasing. It would be interesting to design tests to always check that everything is ok,
If you agree, you could create a new TODO issue where all the ideas could be inserted.

**Comment by lephisto** [comment]
Yes, feedback is much appreciated..

**Pull request merged**
