### PR TITLE
Added Doc, refactor status() function

### PR DESCRIPTION
**Pull request by lephisto**
Refactored status() function, Added extensible doc for qemu-ga and basic principles.

### CODE REVIEW

**Comment by franklupo** [comment]
Hi,
The cron_action_job function doesn't contain the new parameters you added. 
We should add them

Best regards

**Comment by lephisto** [comment]
Ah okay, i wasn't aware that it explicitly needs to be set. Will look into it.

**Comment by franklupo** [comment]
News?

**Comment by lephisto** [comment]
It's in now.. please doubletest..

**Pull request merged**
